name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Login to Docker hub
      run: docker login --username ${{ secrets.DOCKER_REPO_USERNAME }} --password ${{ secrets.DOCKER_REPO_PASSWORD }}
    - name: Build the Docker image for linux
      run: docker build --rm --pull -t xpload/webapi:x64 -f WebApi/Dockerfile .
    - name: Build the Docker image for arm32
      run: docker build --rm --pull -t xpload/webapi:arm32 -f WebApi/Dockerfile.debian-arm32 .
    - name: Set Docker to experimental
      run: export DOCKER_CLI_EXPERIMENTAL=enabled
    - name: Create Docker manifest
      run: docker manifest create xpload/webapi:latest xpload/webapi:arm32 xpload/webapi:x64
    - name: Push Docker manifest
      run: docker manifest push xpload/webapi:latest
